[package]
name = "tile-packer"
version = "0.1.0"
edition = "2018"

[dependencies]
#spritesheet-generator = { git = "https://github.com/slyedoc/spritesheet-generator.git" }
spritesheet-generator = { git = "../spritesheet-generator" }
clap = "3.0.0-beta.2"

